### ISSUE TITLE
Travis test problems

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCore#353]
The Travis CI is sometimes failing.  Running again it usually works:

Leaving test case "invalid_number_dimensions"; testing time: 712mks
Entering test case "basic_1D_operation"
Testing 1D input arrays: 20 Channels with a single scalar value. Averaging=1 samples.
/home/travis/.travis/job_stages: line 104: 17605 Segmentation fault      (core dumped) ./bin/linux-x86_64/plugin-test --log_level=test_suite
The command "./bin/linux-x86_64/plugin-test --log_level=test_suite" exited with 139.

@brunoseivam suspects a race condition, and I think he is right.  We have seen this in the past, because the test framework only exists for a short time.  I think this time it is probably the callbacks from the plugin to the driver to increment or decrement the queuedArrays counter.

 However, I am unable to reproduce this problem on my machine.  I have tried dozens of times.  Can someone else try to reproduce it and track it down.

**Comment by brunoseivam** [comment]
I got it to crash under `gdb`. This smells like a race condition to me:

```#1  0x0000000000ca28a3 in epicsEventWait (pevent=0x0) at ../../src/osi/os/posix/osdEvent.c:99```

`pevent` being zero probably means it's being freed too soon. I'll investigate.


```
(gdb) r
Starting program: /home/martins/epics/areaDetector/ADCore/bin/linux-x86_64-debug/plugin-test --log_level=test_suite
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running 33 test cases...
Entering test suite "NDPlugin Tests"
Entering test suite "CircularBuffTests"
Entering test case "test_BufferWrappingAndStatusMessages"
Leaving test case "test_BufferWrappingAndStatusMessages"; testing time: 1920mks
Entering test case "test_OutputCount"
Leaving test case "test_OutputCount"; testing time: 936mks
Entering test case "test_PreBufferOrder"
Leaving test case "test_PreBufferOrder"; testing time: 697mks
Leaving test suite "CircularBuffTests"
Entering test suite "NDFileHDF5Tests"
Entering test case "test_createDatasetType"
Leaving test case "test_createDatasetType"; testing time: 6486mks
Entering test case "test_Capture"
Leaving test case "test_Capture"; testing time: 6542mks
Entering test case "test_DatasetLayout1"
Leaving test case "test_DatasetLayout1"; testing time: 10628mks
Leaving test suite "NDFileHDF5Tests"
Entering test case "test_AttributeOriginalDataset"
Leaving test case "test_AttributeOriginalDataset"; testing time: 10265mks
Entering test case "test_AttributeDimensionalDataset"
Leaving test case "test_AttributeDimensionalDataset"; testing time: 13099mks
Entering test case "test_ExtraDatasetDimensions"
Leaving test case "test_ExtraDatasetDimensions"; testing time: 1295mks
Entering test case "test_TenExtraDimensions"
Leaving test case "test_TenExtraDimensions"; testing time: 1308112mks
Entering test case "test_PluginExtraDimensions"
Leaving test case "test_PluginExtraDimensions"; testing time: 12667mks
Entering test suite "PosPluginTests"
Entering test case "test_LoadingDataPoints"
Entity: line 1: parser error : Specification mandate value for attribute xml
<pos_layout><bad xml string</position>
                     ^
Entity: line 1: parser error : attributes construct error
<pos_layout><bad xml string</position>
                     ^
Entity: line 1: parser error : Couldn't find end of Start Tag bad
<pos_layout><bad xml string</position>
                     ^
/tmp/invalid_points.xml:1: parser error : Specification mandate value for attribute xml
<pos_layout><bad xml string</position>
                     ^
/tmp/invalid_points.xml:1: parser error : attributes construct error
<pos_layout><bad xml string</position>
                     ^
/tmp/invalid_points.xml:1: parser error : Couldn't find end of Start Tag bad
<pos_layout><bad xml string</position>
                     ^
Leaving test case "test_LoadingDataPoints"; testing time: 2260mks
Leaving test suite "PosPluginTests"
Entering test suite "TimeSeriesPluginTests"
Entering test case "validate_input_NDArrays"
Validating the input NDArrays - if any of these fail the test-cases are also likely to fail
Leaving test case "validate_input_NDArrays"; testing time: 966mks
Entering test case "invalid_number_dimensions"
Expecting stdout message "error, number of array dimensions..."
2018/12/03 09:54:52.003 NDPluginTimeSeries::processCallbacks: error, number of array dimensions must be 1 or 2
Leaving test case "invalid_number_dimensions"; testing time: 1136mks
Entering test case "basic_1D_operation"
Testing 1D input arrays: 8 Channels with a single scalar value. Averaging=10 samples. Time series length=20
Leaving test case "basic_1D_operation"; testing time: 1361mks
Entering test case "basic_2D_operation"
Testing 2D input arrays: 3 channels with 20 elements. Averaging=10 Time series length=20
Leaving test case "basic_2D_operation"; testing time: 1058mks
Entering test case "circular_2D_operation"
Testing 2D input arrays: 3 channels with 20 elements. Averaging=10 Time series length=20
Leaving test case "circular_2D_operation"; testing time: 947mks
Entering test case "output_NDArray_fixed_mode"
Checking output NDArray in Fixed Mode, 2D input: 3 channels with 20 elements. Averaging=10 Time series length=20
Leaving test case "output_NDArray_fixed_mode"; testing time: 966mks
Entering test case "trigger_output_NDArray_circular_mode"

Thread 68 "TS_27_updateQue" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdb910b80 (LWP 21397)]
__GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
67	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:67
#1  0x0000000000ca28a3 in epicsEventWait (pevent=0x0) at ../../src/osi/os/posix/osdEvent.c:99
#2  0x000000000064b9a3 in asynNDArrayDriver::updateQueuedArrayCount (this=0x1981d30) at ../asynNDArrayDriver.cpp:713
#3  0x000000000064b981 in updateQueuedArrayCountC (drvPvt=0x1981d30) at ../asynNDArrayDriver.cpp:706
#4  0x0000000000ca06a4 in start_routine (arg=0x19529e0) at ../../src/osi/os/posix/osdThread.c:403
#5  0x00007ffff79166ba in start_thread (arg=0x7fffdb910b80) at pthread_create.c:333
#6  0x00007ffff675941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```
